# Dependencies
markdown:            redcarpet
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:            Dataologist
tagline:          'Ramblings of yet another dataist.'
description:      'Blog of The Dataologist. More to come.'
url:              http://www.dataologist.com

author:
  name:           'The Dataologist'
  url:            http://www.dataologist.com/thedataologist
  gravatar:       https://en.gravatar.com/thedataologist
  photo:          https://1.gravatar.com/avatar/d70d0286fbf7c1cffbd02731af5f85ed?s=400&d=mm
  description:   'A blog following the journey of a dataist. Finding, using and reporting on tools that further data science.'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/thedataologist/dataologist.github.io

theme: jekyll-theme-time-machine
