# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:            Dataologist
tagline:          'Ramblings of a data <s>scientist</s> student.'
description:      'Blog of The Dataologist. More to come.'
url:              http://www.dataologist.com

author:
  name:           'The Dataologist'
  url:            http://codinfox.github.io
  gravatar:       https://en.gravatar.com/thedataologist
  photo:          http://2.gravatar.com/avatar/00000000000000000000000000000000?size=350
  description:   'A data scientist in the making with knowledge of tools like Splunk to gather, search, analyze machine-generated big data.'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/thedataologist/dataologist.github.io

theme: jekyll-theme-time-machine
